name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the latest code from the repository
    - name: Checkout the repository
      uses: actions/checkout@v2

    # Step 2: Set up Google Cloud SDK with the correct version
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1  # Use v1 or v2 instead of master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        project_id: wuarpservices

    # Step 3: Deploy to Compute Engine
    - name: Deploy to Compute Engine
      run: |
        gcloud compute ssh wuarps-deployment-vm \
          --project=wuarpservices \
          --zone=us-central1-a \
          --command="cd /home/ConstDesignWuarps/Mar_y_tierra && git pull && sudo systemctl restart flaskapp.service"
