name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the latest code from the repository
    - name: Checkout the repository
      uses: actions/checkout@v3

    # Step 2: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: wuarpservices

    # Step 4: Deploy to Compute Engine (VM in us-central1-b)
    - name: Deploy to Compute Engine
      run: |
        gcloud compute ssh cloud-deployment-gce-java-mig-green-gf7f \  # Use the correct VM name
          --project=wuarpservices \
          --zone=us-central1-b \  # Use the correct zone for the VM
          --command="cd /home/ConstDesignWuarps/Mar_y_tierra && git pull && sudo systemctl restart flaskapp.service"
