name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the latest code from the repository
    - name: Checkout the repository
      uses: actions/checkout@v3  # Use the latest version

    # Step 2: Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1  # Add authentication step
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1  # Use v1 but remove deprecated inputs
      with:
        version: 'latest'
        project_id: wuarpservices

    # Step 4: Deploy to Compute Engine
    - name: Deploy to Compute Engine
      run: |
        gcloud compute ssh wuarps-deployment-vm \
          --project=wuarpservices \
          --zone=us-central1-a \
          --command="cd /home/ConstDesignWuarps/Mar_y_tierra && git pull && sudo systemctl restart flaskapp.service"
